task:
  name: build
  timeout_in: 120m
  freebsd_instance:
    matrix:
      image_family: freebsd-13-0-snap
#      image_family: freebsd-12-1
#      image_family: freebsd-11-3-snap
  env:
    CIRRUS_CLONE_DEPTH: 1
    MAKE_FLAGS: -j 2
    PACKAGES: autoconf automake libtool pkgconf gcc libxml2 freetype2 png curl build xorg gettext gettext-tools git sdl sdl_gfx sdl_image sdl_mixer sdl_net sdl_ttf git gdb valgrind
    LDFLAGS: -L${LOCALBASE}/lib -lintl

  first_script:
    ./run.sh

  check1_script:
    - gcc --version || true
    - clang --version || true
    - echo ${LOCALBASE}
    - echo ${LDFLAGS}

  pkginstall_script:
    echo "test line" >config.log
    echo "line2" >qqq

  test_artifacts:
    path: "config.log"

  all_artifacts:
    path: "*"

#task:
#  name: Windows
#  windows_container:
#    image: cirrusci/windowsservercore:2019
#
#  winfirst_script:
#    dir
